name: CI

on:
  pull_request:
    paths:
      - 'native/KotlinIOS/Authentication/**'
jobs:
 
  test:
    name: Run all Unit Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: cd native/KotlinIOS xcodebuild -workspace Minimise.xcworkspace -scheme Authentication -destination 'platform=iOS Simulator,name=iPhone 11' test
